#!/usr/bin/env bash
# This bash script pings an IP address passed as a string argument
if [ $# -lt 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit "2"
else
	ping -c 5 "$1"
fi
